# Generated by Django 5.0.6 on 2024-06-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='instagram',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
