# Generated by Django 5.1.4 on 2025-01-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuarios_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='apellido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='mail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
