# Generated by Django 5.0.6 on 2024-08-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuarios_foto_alter_usuarios_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
