# Generated by Django 5.1.4 on 2025-03-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuarios_apellido_usuarios_mail_usuarios_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='cargado',
            field=models.DateField(),
        ),
    ]
