# Generated by Django 5.0.6 on 2025-04-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuarios_cargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='domicilio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
