# Generated by Django 5.1.4 on 2025-01-05 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gastos',
            options={'verbose_name': 'Gasto', 'verbose_name_plural': 'Gastos'},
        ),
    ]
