# Generated by Django 5.1.4 on 2025-01-06 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_gastos_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastos',
            name='fijo_variable',
        ),
        migrations.RemoveField(
            model_name='gastos',
            name='mes',
        ),
    ]
