# Generated by Django 5.1.4 on 2025-03-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_rename_fecha_pago_gastos_fecha_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='fecha',
            field=models.DateField(),
        ),
    ]
