# Generated by Django 5.0.6 on 2024-08-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_pagos_modo_pago_pagos_pase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='modo_pago',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='pase',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
